# Generated by Django 3.2.5 on 2021-08-29 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_auto_20210829_0150'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['tags', 'name']},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='order',
            name='transaction_id',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
